Repository open-domains/register, pull requests merged in 2023-06, with the labels that each got.

#368 Create hastebin.is-local.org.json
  domains/hastebin.is-local.org.json
Labels: awaiting response, cla required

#373 Create narmis.is-cool.dev
  domains/narmis.is-cool.dev.json
Labels: GitHub Pages

#349 Create aws.is-local.org.json
  aws.is-local.org.json
Labels: DON'T MERGE, NS records, awaiting response

#385 Register josh.is-cool.dev
  domains/josh.is-cool.dev.json
Labels: DON'T MERGE, awaiting response, cla required
