Repository open-domains/register, pull requests merged in 2024-01, with the labels that each got.

#817 Register shrimp-ai.localplayer.dev
  domains/shrimp-ai.localplayer.dev.json
Labels: Invalid: NS Records, Awaiting Response

#818 Create astra.is-cool.dev.json
  domains/astra.is-cool.dev.json
Labels: Awaiting Response, Invalid: File

#824 Create this.is-cool.dev.json
  domains/this.is-cool.dev.json
Labels: Invalid: Records

#846 Change records for justincodingprojects.is-cool.dev.json
  domains/justincodingprojects.is-cool.dev.json
Labels: Awaiting Response, CLA Required, Invalid: Records

#860 Create spicydevs.is-local.org.json
  domains/spicydevs.is-local.org.json
Labels: Awaiting Response, CLA Required

#859 Create spicydevs.localplayer.dev.json
  domains/spicydevs.localplayer.dev.json
Labels: Awaiting Response, CLA Required

#893 Deleted unused domain and updated the other one
  domains/yor.is-local.org.json
  domains/yuki.is-local.org.json
Labels: Invalid: Records

#889 Register toyab.is-local.org
  domains/toyab.is-cool.dev.json
  domains/toyab.is-local.org.json
Labels: Awaiting Response, Invalid: Records
