Repository open-domains/register, pull requests merged in 2024-05, with the labels that each got.

#1124 feat: changing file to reflect changes
  README.md
Labels: Waiting: Maintainer Decision

#1150 register eagos.localplayer.dev
  domains/eagos.localplayer.dev.json
Labels: CLA Required

#1177 Create saneseo.localplayer.dev
  domains/saneseo.localplayer.dev.json
Labels: CLA Required

#1174 Create anmail.is-local.org.json
  domains/anmail.is-local.org.json
Labels: Awaiting Response

#1188 Create ukrio.is-cool.dev.json
  domains/ukrio.is-cool.dev.json
Labels: Awaiting Response, Waiting: Reasoning
