Repository open-domains/register, pull requests merged in 2024-06, with the labels that each got.

#1247 Create *.xzonix.is-cool.dev.json
  domains/*.xzonix.is-cool.dev.json
Labels: Awaiting Response, Invalid: Records, Invalid: File

#1241 Create vonik.is-cool.dev
  domains/vonik.is-cool.dev.json
Labels: Awaiting Response, Invalid: File

#1269 Create botanybase.is-local.org.json
  domains/botanybase.is-local.org.json
Labels: Awaiting Response, Invalid: File

#1268 create co.is-local.org
  domains/_github-pages-challenge-hexo-theme.co.json
  domains/co.is-local.org.json
Labels: Awaiting Response, Invalid: Records

#1272 Update *.business.is-local.org.json
  domains/*.business.is-local.org.json
Labels: Awaiting Response, CLA Required, Waiting: Reasoning

#1284 domain req for: vamika.is-local.org
  domains/vamika.is-local.org.json
Labels: Awaiting Response, Invalid: File

#1285 Domain Request: ron.localplayer.dev
  domains/ron.localplayer.dev.json
Labels: Awaiting Response, Invalid: File

#1295 Update wacky.is-cool.dev.json
  domains/_github-pages-challenge-Arzejames.wacky.is-not-a.dev.json
  domains/wacky.is-cool.dev.json
Labels: Awaiting Response, Invalid: Records

#1300 mycodelab-is.cool.dev.json
  domains/mycodelab.is-cool.dev.json
Labels: Awaiting Response, Invalid: File

#1308 Create *.jvgbet.is-cool.dev.json
  domains/*.jvgbet.is-cool.dev.json
Labels: Awaiting Response, Waiting: Reasoning, Waiting: Maintainer Decision

#1305 Create this-mc-server.is-cool.dev.json
  domains/this-mc-server.is-cool.dev.json
Labels: Awaiting Response, Invalid: File

#1309 Create yash-dj-films-and-studio.is-local.org.json
  domains/yash-dj-films-and-studio.is-local.org.json
Labels: Awaiting Response, Invalid: File

#1289 Request domain lophoctinhthuong.is-local.org
  domains/lophoctinhthuong.is-local.org.json
Labels: Awaiting Response, Invalid: File

#1315 Register git-gamble.is-cool.dev
  domains/git-gamble.is-cool.dev.json
Labels: Awaiting Response, Invalid: File

#1318 Update record for lophoctinhthuong.is-local.org
  domains/lophoctinhthuong.is-local.org.json
Labels: Awaiting Response, Invalid: Records
