Repository open-domains/register, pull requests merged in 2024-07, with the labels that each got.

#1340 Create srimaruthiricemill.domain.json
  domains/srimaruthiricemill.localplayer.dev.json
Labels: Awaiting Response, Invalid: Records

#1352 Update NS record tasin.is-cool.dev.json
  domains/tasin.is-cool.dev.json
Labels: Awaiting Response, Waiting: Reasoning

#1358 Create esb.is-cool.dev.json
  domains/esb.is-cool.dev.json
Labels: Awaiting Response, Invalid: Inaccessible Site

#1372 Update mycodelab.is-cool.dev.json
  domains/mycodelab.is-cool.dev.json
Labels: Awaiting Response, Invalid: Records

#1376 Create Gunman.is-a-fullstack.dev.json
  domains/gunman.is-a-fullstack.dev.json
Labels: Awaiting Response, CLA Required

#1385 Create comi.is-local.org.json
  domains/comi.is-local.org.json
Labels: Awaiting Response, Invalid: Records

#1393 Create zenshi.is-cool.dev.json
  domains/zenshi.is-cool.dev.json
Labels: DON'T MERGE, Awaiting Response
