Repository open-domains/register, pull requests merged in 2024-04, with the labels that each got.

#1057 Create short_d.is-cool.dev.json
  domains/drago.is-cool.dev.json
Labels: Awaiting Response, Invalid: File

#1041 Create isg32.is-cool.dev.json
  domains/isg32.is-cool.dev.json
Labels: Awaiting Response, CLA Required

#1075 shaurika.is-cool.dev
  domains/*.shaurika.is-cool.dev.json
Labels: Awaiting Response, CLA Required

#1089 Create niky.is-local.org.json
  domains/niky.is-local.org.json
Labels: CLA Required

#1114 danlp6.is-local.org and danlp1.is-local.org
  domains/danlp1.is-local.org.json
  domains/danlp6.is-local.org.json
  domains/repo.is-local.org.json
Labels: Awaiting Response, CLA Required
