Repository open-domains/register, pull requests merged in 2025-01, with the labels that each got.

#1906 Create _acme-challenge.sctech.localplayer.dev.json
  domains/_acme-challenge.sctech.localplayer.dev.json
Labels: CLA Signed

#1905 🤦🤦🤦🤦🤦 I am so stupid github Create _github-pages-challenge-py660.python660.is-local.org.json
  domains/_github-pages-challenge-py660.python660.is-local.org.json
Labels: CLA Signed

#1904 Create m4sterle.json
  domains/m4sterle.is-not-a.dev.json
Labels: CLA Signed

#1899 add nahor.is-local.org
  domains/nahor.is-local.org.json
Labels: Invalid: File, CLA Signed

#1913 Create *.bots.maragi.is-cool.dev
  domains/*.bots.maragi.is-cool.dev.json
Labels: CLA Signed

#1912 update racknerdzxu.is-local.org non proxy due to block by cloudflare access from CN
  domains/racknerdzxu.is-local.org.json
Labels: CLA Signed

#1918 Update racknerdzxu.is-local.org.json to try cdn again
  domains/racknerdzxu.is-local.org.json
Labels: CLA Signed

#1916 Update and rename 43.is-cool.dev.json to 93.localplayer.dev.json
  domains/93.localplayer.dev.json
Labels: CLA Signed

#1914 Create aditya.domain.json
  domains/aditya.is-cool.dev.json
Labels: Invalid: File, CLA Signed

#1920 Update racknerdzxu.is-local.org.json proxy still not working at CN
  domains/racknerdzxu.is-local.org.json
Labels: CLA Signed

#1921 Create *.bernardo-silva.is-cool.dev
  domains/*.bernardo-silva.is-cool.dev.json
Labels: Invalid: File, CLA Signed

#1923 Create finn.is-a-fullstack.dev.json
  domains/finn.is-a-fullstack.dev.json
Labels: CLA Signed

#1922 Create kawrr.is-a-fullstack.dev
  domains/kawrr.is-a-fullstack.dev.json
Labels: Invalid: Records, Invalid: File, CLA Signed, Invalid JSON, Invalid DNS

#1925 Add `toronto.is-local.org`
  domains/toronto.is-local.org.json
Labels: CLA Signed

#1929 Commit of pixillium.is-cool.dev
  domains/pixillium.is-cool.dev.json
Labels: CLA Signed

#1930 Create philip.is-cool.dev.json
  domains/philip.is-cool.dev.json
Labels: CLA Signed

#1924 Create *.bernardo-silva.is-cool.dev.json
  domains/*.bernardo-silva.is-cool.dev.json
  domains/bernardo-silva.is-cool.dev.json
Labels: CLA Signed

#1931 Create cookie4u.is-cool.dev.json
  domains/cookie4u.is-cool.dev.json
Labels: CLA Signed

#1932 Create minitor.is-local.org
  domains/minitor.is-local.org.json
Labels: CLA Signed

#1933 Update minitor.is-local.org.json
  domains/minitor.is-local.org.json
Labels: CLA Signed

#1947 Create sneazy25.localplayer.dev.json
  domains/sneazy25.localplayer.dev.json
Labels: CLA Signed

#1945 Create ids.is-not-a.dev.json
  domains/ids.is-not-a.dev.json
Labels: CLA Signed

#1946 Create jayesh.is-cool.dev.json
  domains/jayesh.is-cool.dev.json
Labels: CLA Signed

#1943 Create stream.darmstadt.localplayer.dev.json
  domains/stream.darmstadt.localplayer.dev.json
Labels: CLA Signed

#1937 move nahor to rohanb
  domains/rohanb.is-local.org.json
Labels: CLA Signed

#1950 Create marclosper.is-a-fullstack.dev.json
  domains/marclosper.is-a-fullstack.dev.json
Labels: CLA Signed

#1938 TdoubleT.is-a-fullstack.dev.json
  domains/tdoublet.is-a-fullstack.dev.json
Labels: Invalid: File, CLA Signed

#1958 changing my domain proxy status
  domains/projectvoid.is-local.org.json
Labels: CLA Signed

#1959 Verify _github-pages-challenge-Clay990.Ishan.is-local.org.json
  domains/_github-pages-challenge-clay990.ishan.is-local.org.json
Labels: CLA Signed

#1963 Merged branch 'main' into ZeroDeaths379-patch-1
  domains/orion.is-cool.dev.json
Labels: CLA Signed

#1965 Add files via upload
  domains/cx.is-cool.dev.json
Labels: Invalid: File, CLA Signed

#1975 Update ababil.is-not-a.dev.json
  domains/ababil.is-not-a.dev.json
Labels: CLA Signed

#1983 Delete my domain
  domains/_github-pages-challenge-the-coding-empire.coding.json
  domains/coding.is-cool.dev.json
Labels: CLA Signed

#1976 undercover game - github pages
  domains/_github-pages-challenge-antebrl.undercover.darmstadt.localplayer.dev.json
  domains/_github-pages-challenge-antebrl.undercover.localplayer.dev.json
  domains/undercover.darmstadt.localplayer.dev.json
  domains/undercover.localplayer.dev.json
Labels: CLA Signed

#1985 Create aerioncloud.is-local.org.json
  domains/aerioncloud.is-local.org.json
Labels: CLA Signed

#1984 Update and rename tooreal.is-a-fullstack.dev.json to lebronjames.loca…
  domains/lebronjames.localplayer.dev.json
Labels: CLA Signed
