Repository open-domains/register, pull requests merged in 2025-07, with the labels that each got.

#2440 Create eclipse.is-not-a.dev.json
  domains/eclipse.is-not-a.dev.json
Labels: CLA Signed

#2448 Request Subdomain yogesh.is-cool.dev
  domains/yogesh.is-cool.dev.json
Labels: CLA Signed

#2450 Patch 1
  domains/dailker.is-cool.dev.json
Labels: CLA Signed

#2455 Create forums.clidewoodrealm.localplayer.dev.json
  domains/forums.clidewoodrealm.localplayer.dev.json
Labels: CLA Signed

#2469 Add toly.is-cool.dev, immich.toly.is-cool.dev
  domains/immich.toly.is-cool.dev.json
  domains/toly.is-cool.dev.json
Labels: CLA Signed

#2387 Update cmx.is-local.org cmx.is-cool.dev
  domains/cmx.is-cool.dev.json
  domains/cmx.is-local.org.json
Labels: Awaiting Response, CLA Signed

#2464 Create hrv-clan.is-local-org.json
  domains/hrv-clan.is-local.org.json
Labels: CLA Signed

#2472 switched servers and have new ip
  domains/litcoemarketplace.is-not-a.dev.json
Labels: CLA Signed

#2467 Update maragi.is-cool.dev.json
  domains/maragi.is-cool.dev.json
Labels: CLA Signed

#2470 Create sgyt.is-local.org.json
  domains/sgyt.is-local.org.json
Labels: CLA Signed

#2490 Create getpixillium.is-cool.dev.json with its sub-sub domains
  domains/_dmarc.getpixillium.is-cool.dev.json
  domains/cka._domainkey.getpixillium.is-cool.dev.json
  domains/cka2._domainkey.getpixillium.is-cool.dev.json
  domains/ckespa.getpixillium.is-cool.dev.json
  domains/getpixillium.is-cool.dev.json
Labels: CLA Signed

#2487 Update nsg.is-local.org.json file - A record array
  domains/nsg.is-local.org.json
Labels: CLA Signed

#2492 Update clidewoodrealm.localplayer.dev.json
  domains/clidewoodrealm.localplayer.dev.json
Labels: CLA Signed

#2497 Update clidewoodrealm.localplayer.dev.json
  domains/clidewoodrealm.localplayer.dev.json
Labels: CLA Signed

#2498 Update and rename playclidewood.localplayer.dev.json to play.clidewoo…
  domains/play.clidewoodrealm.localplayer.dev.json
Labels: CLA Signed

#2491 Create rotur.is-cool.dev.json
  domains/rotur.is-cool.dev.json
Labels: CLA Required

#2501 fix: SRV record validation
  tests/domains.test.js
  tests/records.test.js
Labels: Bug, Enhancement

#2519 Fixed errors.
  domains/sanal.is-cool.dev.json
Labels: CLA Required

#2520 Create tanbaycu.is-a-fullstack.dev.json
  domains/tanbaycu.is-a-fullstack.dev.json
Labels: CLA Required
