Repository open-domains/register, pull requests merged in 2025-02, with the labels that each got.

#1990 Update A Records
  domains/catboy.localplayer.dev.json
  domains/memoryedge.localplayer.dev.json
  domains/themeddler.localplayer.dev.json
Labels: CLA Signed

#1972 Create *.voot.is-not-a.dev.json
  domains/*.voot.is-not-a.dev.json
Labels: Awaiting Response, CLA Signed

#1988 xixix.is-local.org
  domains/xixix.is-local.org.json
Labels: CLA Signed

#1994 Update maragi.is-cool.dev.json
  domains/maragi.is-cool.dev.json
Labels: CLA Signed

#1997 Update projectvoid.is-local.org.json
  domains/projectvoid.is-local.org.json
Labels: CLA Signed

#1995 Update maragi.is-cool.dev.json
  domains/maragi.is-cool.dev.json
Labels: CLA Signed

#2003 want to switch sub domain names. please merge this asap
  domains/curiolearn.is-local.org.json
Labels: CLA Signed

#2007 Create *.bn.is-local.org.json
  domains/*.bn.is-local.org.json
  domains/bn.is-local.org.json
Labels: CLA Signed

#2002 Add new domain configuration for teleserver.is-local.org
  domains/teleserver.is-local.org.json
Labels: CLA Signed

#1998 Create finch.is-cool.dev.json
  domains/finch.is-cool.dev.json
Labels: CLA Signed

#1967 Create *oli-mebberson.is-cool.dev.json
  domains/oli-mebberson.is-cool.dev.json
Labels: Awaiting Response, Invalid: File, CLA Signed

#2015 Create luap.is-cool.dev.json
  domains/luap.is-cool.dev.json
Labels: Invalid: File, CLA Signed

#2019 Create innocentzero.is-not-a.dev.json
  domains/innocentzero.is-not-a.dev.json
Labels: CLA Signed

#2021 Update argchatpi.is-not-a.dev.json
  domains/argchatpi.is-not-a.dev.json
Labels: CLA Signed

#2029 switching domain names. please merge this ASAP
  domains/curiolearn.localplayer.dev.json
Labels: CLA Signed

#2028 Create arg4020.is-local.org.json
  domains/arg4020.is-local.org.json
Labels: CLA Signed

#2025 yoan.is-not-a.dev domain
  domains/yoan.is-not-a.dev.json
Labels: CLA Signed

#2030 Create duong-viet-hoang.is-a-fullstack.dev.json
  domains/duong-viet-hoang.is-a-fullstack.dev.json
Labels: CLA Signed

#2031 Create pvtunnel.localplayer.dev.json
  domains/pvtunnel.localplayer.dev.json
Labels: Invalid: Records, CLA Signed

#2038 Request for novk.localplayer.dev
  domains/novk.localplayer.dev.json
Labels: CLA Signed

#2037 Create HiddenPicture.is-not-a.dev.json
  domains/HiddenPicture.is-not-a.dev.json
Labels: CLA Signed

#2045 Create moca.is-cool.dev.json
  domains/moca.is-cool.dev.json
Labels: CLA Signed

#2047 Delete domains/curiolearn.localplayer.dev.json
  domains/curiolearn.localplayer.dev.json
Labels: CLA Signed

#2042 add suvidhajs.is-cool.dev
  domains/suvidhajs.is-cool.dev.json
Labels: CLA Signed

#2040 Update comments-zishu.is-local.org.json
  domains/comments-zishu.is-local.org.json
Labels: CLA Signed

#2043 Create photo-serv5412.domain.json
  domains/photo-serv5412.domain.json
Labels: CLA Signed

#2046 Different Link and A record as my other record isn't working and is c…
  domains/kawrr.is-a-local.org.json
Labels: CLA Signed

#2044 Update naf.is-cool.dev.json
  domains/naf.is-cool.dev.json
Labels: CLA Signed

#2062 Create nexus.localplayer.dev.json
  domains/nexus.localplayer.dev.json
Labels: CLA Signed

#2075 Delete domains/pvtunnel.localplayer.dev.json
  domains/pvtunnel.localplayer.dev.json
Labels: CLA Signed

#2067 Update biblionest.is-local.org.json
  domains/biblionest.is-local.org.json
Labels: CLA Signed

#2074 Fixed Directory Issue now it should be in the domains directory oof
  domains/doge.localplayer.dev.json
Labels: CLA Signed

#2082 Create cyiwdio.localplayer.dev.js
  domains/cyiwdio.localplayer.dev.json
Labels: CLA Signed
