Repository open-domains/register, pull requests merged in 2025-09, with the labels that each got.

#2635 Request subdomain ammar.is-cool.dev
  domains/ammar.is-cool.dev.json
Labels: CLA Required

#2695 Create csenotes.is-cool.dev.json
  domains/csenotes.is-cool.dev.json
Labels: Invalid: Records, Invalid: File, Invalid JSON

#2696 feat: new test case to make sure TXT records are arrays
  tests/json.test.js
Labels: Maintainer
