Repository open-domains/register, pull requests merged in 2025-04, with the labels that each got.

#2061 feat: add personal domains
  domains/app.is-cool.dev.json
  domains/app.is-local.org.json
  domains/jonathan.is-a-fullstack.dev.json
  domains/jonathan.is-cool.dev.json
  domains/project.is-cool.dev.json
  domains/project.is-local.org.json
  domains/site.is-cool.dev.json
  domains/site.is-local.org.json
Labels: Awaiting Response, CLA Signed

#2087 Create *.jvsp.localplayer.dev
  domains/*.jvsp.localplayer.dev
  domains/_discord.jvsp.is-cool.dev
Labels: CLA Signed

#2177 Update clidewoodrealm.localplayer.dev.json
  domains/clidewoodrealm.localplayer.dev.json
Labels: CLA Signed

#2103 Create vizzy.domain.json
  domains/vizzy.domain.json
Labels: CLA Signed

#2137 Add jessica.is-not-a.dev
  domains/jessica.is-not-a.dev.json
Labels: CLA Signed

#2173 Create knowledge-base.is-local.org.json
  domains/knowledge-base.is-local.org.json
Labels: Awaiting Response, CLA Signed

#2180 Create try888.is-cool.dev.json
  domains/try888.is-cool.dev.json
Labels: CLA Signed

#2174 Add kotofey.is-not-a.dev
  domains/*.app.sctech.localplayer.dev.json
  domains/kotofey.is-not-a.dev.json
Labels: CLA Signed, Invalid DNS

#2130 Create racknerdcdnzxu.is-cool.dev.json
  domains/racknerdcdnzxu.is-cool.dev.json
Labels: Awaiting Response, CLA Signed

#2136 Create brew.is-not-a.dev.json
  domains/brew.is-not-a.dev.json
Labels: CLA Signed

#2181 fix: two invalid files
  domains/_vercel.is-cool.dev
  domains/jvsp.localplayer.dev
Labels: CLA Signed

#2184 chore: invalid domain format removals
  domains/_github-pages-challenge-chikes-web-turquoisetnt.chikes.json
  domains/_github-pages-challenge-hexo-theme.co.json
  domains/_github-pages-challenge-ilrc.it.json
  domains/_github-pages-challenge-ilrc.one.json
  domains/comensal.is-not-a-dev.json
  domains/elora.is-not-a-dev.json
  domains/moviebypass.localplayer.json
  domains/stpeterlib.is-local-org.json
Labels: CLA Signed

#2185 feat: more validation testing
  localtests/lowercase.js
  localtests/test.js
  package.json
Labels: CLA Signed

#2111 Create zmail._domainkey.pixillium.is-cool.dev.json
  domains/zmail._domainkey.pixillium.is-cool.dev.json
Labels: CLA Signed

#2186 Update and rename wisard-gaming.is-not-a.dev.json to ram-llc.is-local…
  domains/ram-llc.is-local.org.json
  domains/wisard-gaming.is-not-a.dev.json
Labels: CLA Signed

#2187 feat: more test cases
  tests/json.test.js
Labels: Enhancement, CLA Signed, Maintainer

#2156 Create lovely.localplayer.dev.json
  domains/lovely.localplayer.dev.json
Labels: CLA Signed

#2192 Create *.cshs.is-not-a.dev.json
  domains/cshs.is-not-a.dev.json
Labels: CLA Signed

#2198 Setting up dns for homelab
  domains/*.luigi.is-cool.dev.json
  domains/luigi.is-cool.dev.json
Labels: CLA Signed

#2196 Create _dmarc.pixillium.is-cool.dev.json
  domains/_dmarc.pixillium.is-cool.dev.json
Labels: CLA Signed

#2193 aethel.localplayer.dev
  domains/aethel.localplayer.dev.json
Labels: CLA Signed

#2200 Update and rename doge.localplayer.dev.json to doge.is-not-a.dev.json | Everything is the same just different doamin because the other one is blocked for me.
  domains/doge.is-not-a.dev.json
Labels: CLA Signed

#2201 Update doge.is-not-a.dev.json | I forgot to change to the new IP sorry
  domains/doge.is-not-a.dev.json
Labels: CLA Signed

#2205 answer github pages challenge
  domains/_github-pages-challenge-ilrc.one.is-a-fullstack.dev.json
Labels: CLA Signed

#2204 feat: update my domains
  domains/miti.is-cool.dev.json
  domains/miti99.is-cool.dev.json
Labels: CLA Signed

#2206 Create vaultic.is-cool.dev.json
  domains/vaultic.is-cool.dev.json
Labels: CLA Signed

#2207 Create default._bimi.pixillium.is-cool.dev.json
  domains/default._bimi.pixillium.is-cool.dev.json
Labels: CLA Signed

#2208 Create babo.is-cool.dev.json
  domains/babo.is-cool.dev.json
Labels: CLA Signed

#2211 Add princevora.is-a-fullstack.dev.json
  domains/princevora.is-a-fullstack.dev.json
Labels: CLA Signed

#2212 NS Records request for aboutuste.localplayer.dev
  domains/_discord.aboutuste.localplayer.dev.json
  domains/aboutuste.localplayer.dev.json
Labels: CLA Signed

#2214 Create princevora.is-cool.dev.json
  domains/princevora.is-cool.dev.json
Labels: CLA Signed

#2220 tabs-mc.is-cool.dev subdomain merge
  domains/tabs-mc.is-cool.dev.json
Labels: CLA Signed

#2221 Create tab-mc.is-cool.dev.json
  domains/tab-mc.is-cool.dev.json
Labels: CLA Signed

#2225 Create ahmed.is-a-fullstack.dev.json
  domains/ahmed.is-a-fullstack.dev.json
Labels: CLA Signed

#2224 Create ame.is-not-a.dev.json
  domains/ame.is-not-a.dev.json
Labels: CLA Signed

#2222 Create *.lumatic.is-cool.dev.json
  domains/lumatic.is-cool.dev.json
Labels: CLA Signed

#2228 Create rohithborana.is-cool.dev.json
  domains/rohithborana.is-cool.dev.json
Labels: CLA Signed

#2231 Create *.app.sctech.localplayer.dev.json
  domains/*.app.sctech.localplayer.dev.json
Labels: CLA Signed

#2233 Update lumatic.is-cool.dev.json
  domains/lumatic.is-cool.dev.json
Labels: CLA Signed

#2234 Create secureconvertph.is-local.org.json
  domains/secureconvertph.is-local.org.json
Labels: CLA Signed

#2236 Forced modification due to previous values ​​not working in mx record
  domains/lumatic.is-cool.dev.json
Labels: CLA Signed

#2241 Add verification txt record
  domains/_github-pages-challenge-ilrc.it.is-local.org.json
Labels: CLA Signed

#2239 Create sokoverse.is-cool.dev.json
  domains/sokoverse.is-cool.dev.json
Labels: CLA Signed

#2245 want to change sub domain and domain names
  domains/mathcentral.is-not-a.dev.json
Labels: CLA Signed

#2246 Create samyeli.is-not-a.dev.json
  domains/samyeli.is-not-a.dev.json
Labels: CLA Signed
